app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path: /logout

setFavourite:
    path: /setFavourite/{characterid}
    controller: AppBundle\Controller\CharactersController::setFavouriteAction

newFavourite:
    path: /newFavourite
    controller: AppBundle\Controller\CharactersController::newFavouriteAction